### PR TITLE
Fix for empty set variable error

### PR DESCRIPTION
**Pull request by Caffetaria**
Fixed server error for the set variable block in Calliope, NXT, Microbit and EV3.

### CODE REVIEW

**Comment by Caffetaria** [comment]
Should I force-push my branch again as the integration tests are passing on my local branch now?

**Comment by boonto** [comment]
Sure

**Comment by boonto** [comment]
Those are the Unit tests by the way, they differ from the integration tests, which only run optionally.

**Comment by Caffetaria** [comment]
Oh okay, thanks for letting me know :)

**Pull request merged**
