### PR TITLE
fix robot drawing before simulation start

### LINKED ISSUE #648: EV3 Simulation Robot Leaving Weird Drawings
**Describe the bug**
 - When using an EV3 Robot in the simulation with a background that the robot can draw on, moving the robot will leave a mark in its original spot

**To Reproduce**
1. Go to EV3 simulation
2. Open a drawable background
3. Move the robot around and observe the drawing

**Expected behavior**
 - The robot to not make any marks until the program has been started

**Screenshots**
EV3 Robot Leaving Weird Marks

**Device information**
 - Type Desktop
 - OS: Windows 10
 - Browser  Chrome 79

**Additional context**
 - If you move the robot fast enough (As shown in the video), you are also able to make weird streaks.

### PR DESCRIPTION
**Pull request by KevinL10**
Fixes #648 

The robot drawing will only occur if the program is running, which is checked by examining the simControl button.

### CODE REVIEW

**Comment by KevinL10** [comment]
Right now I can't find any alternatives, but are there any things that occur differently when the program is running? For example, if the program is running, then the stop/play button will be different.

However, stop/play uses the css
simcontrol

**Comment by boonto** [comment]
@bjost2s is there another way to to determine if the simulation is running?
If not, we should probably add one, you can save the state in a variable and start/stop with the specific events. This should be a lot cleaner.

**Comment by boonto** [comment]
Can you add your changes from #740 here, both can be in the same pull request.
I'll also give some feedback for that here:
The `simRunning` should be declared and exposed in the `simulation.js` in the `setPause(...)` method.
Here, the state of the button and the simulation is changed and the variable could be changed as well. Then the exported method `isSimRunning` can be used in the `scene.js` similar to what you already did.

**Comment by boonto** [comment]
Closed due to inactivity.

**Pull request closed without merging**
