### PR TITLE
Fix for multiple robot views in EV3 when new backgrounds are uploaded

### PR DESCRIPTION
**Pull request by Caffetaria**
This fixes the issue of multiple robot views when two or more backgrounds are uploaded in EV3.

### CODE REVIEW

**Comment by boonto** [comment]
The problem seems to be fixed but the robot view does not open in the multiple simulation anymore.
Lucky I checked that. Do you think you can find a way to work around this?

**Comment by Caffetaria** [comment]
Sure...I'll work on it right away

**Comment by Caffetaria** [comment]
@boonto The problem seems to be fixed with the latest commit.
The erroneous line causing the problem in the multiple robot simulation was `$("#svg" + this.id).hide();` 
Additionally, this line is not used in robot.nxt.js either and that is working fine.

**Comment by boonto** [comment]
Merged in 5d28e2c97c600fd3ec4e06b3fe43b1682d98bb47.

**Pull request closed without merging**
