### PR TITLE
Fix issue #685

### PR DESCRIPTION
**Pull request by Prantikc22**
The documentation regarding the changes are attached herewith. [Issue#685_Fixes.docx](https://github.com/OpenRoberta/openroberta-lab/files/5202428/Issue.685_Fixes.docx)

### CODE REVIEW

**Comment by Prantikc22** [comment]
Proposed fixes for Issue #685

1. What shortcuts would best represent the actions?

CTRL + 1: Import Source code to compile
CTRL + 2: Import Nepo code to compile
CTRL + 3: Initiate Debugger
Ctrl + S: Save the program in your computer
Ctrl + Alt + S: Save the program in the server
Ctrl + P: Create a new program
Ctrl + E: Save the configuration
Ctrl + Alt + R: Run the program
Ctrl + C: Show the source code
Ctrl + Alt + C: Show the source code editor
Ctrl + Alt + J: Switch robot
Ctrl + Y: Start the welcome tour

Appropriate changes are made in the menucontroller.js file

More shortcuts can be added if needed. Currently this are the important ones that were identified.

2. How to show the shortcut to the user?

Under the help dropdown list a new item has been added which is “keyboard shortcut”. By clicking this a list of shortcuts will appear. This is how the keyboard shortcuts can be shown to users.

In index.html

Added line 161 to create new dropdown item for the keyboard shortcut modal
Added lines from 1123 to 1154 for the keyboard shortcut modal

**Comment by boonto** [comment]
Thanks! Some notes:
- There's also the other "debugging" shortcuts Ctrl + 4 - 6? those won't be changed, correct?
- Saving sounds sensible
- Ctrl + P is used for the printing feature of the browser, which is may be used by teachers sometimes
- Why E for saving the configuration? Couldn't that be Ctrl + Alt + S as well, since the user is in the config tab?
- For running a program a shortcut without an extra key might be nice, as that should be one of the most often used ones
- Ctrl + C probably shouldn't be overridden
- Ctrl + Alt + J is awkward to use with one hand
- I don't think the welcome tour needs a shortcut

I think a list of shortcuts is the bare minimum of documentation, but won't really help users that don't know about shortcuts at all. Maybe a small, slightly faded text of the shortcut should be on the right side of the menu entries? Similar to most desktop programs. What do you think?
What about the simulation?

**Comment by Prantikc22** [comment]
Thanks for the feedback.

- The other debugging shortcuts Ctrl + 4 - 6 won't be changed. 

- I will change Ctrl + P, Ctrl + S and Ctrl + Alt + J to make it more user friendly as you rightly suggested.

- For saving the program and configuration the same function is called with different parameter. So Ctrl + S should work for saving the configuration as well. I will remove Ctrl + E in that case.

- Welcome tour shortcut will be removed.

I created a new option item under the "Help" dropdown because I thought a user who would need help will select it and would see the shortcuts as well. But I think your suggestion is better and would implement that in the next commit.

Some shortcuts regarding the simulation will also be added in the next commit.

**Comment by boonto** [comment]
The option in the help window doesn't hurt and should probably stay.
Right now everything is hardcoded, including the description. Can you structure it differently, so that the implementation + it's documentation would come from the same file?
Also think about extracting all of the ifs in the `menu.controller.js`, maybe a shortcut controller makes sense? I am not sure about the best solution here, but just adding everything into the menu controller isn't nice.

**Comment by Prantikc22** [comment]
Yes, sure I will look into improving the structure of files as per your suggestions.

**Comment by Prantikc22** [comment]
Now the keyboard shortcuts are not inside the index.html file. They have been authored in the menu.controller.js file with an array and they are passed onto the html file where they get printed. The structure has been improved. 

Other than that, with the new commit, the most important change is the displaying of the keyboard shortcuts on the right side of the menu options as you earlier wanted it to be. A screenshot of this is attached herewith.
shortcutsInMenu

**Pull request closed without merging**
