### PR TITLE
Fix 1071

### PR DESCRIPTION
**Pull request by rishabhdeepsingh**
# Description
`getFirstMotor(side)` might results in `null` value and calling `getUserDefinedPortName()` on top of that will throw NPE. which then fails to open source code editor. 

Fixes # (issue)
- #1071 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?
The source code editor is now working properly

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by aykborstelmann — APPROVED** [review]
LGTM 👍🏻 
Do you want to squash this yourself, so I can i rebase it or do you prefer me to sqash it ? (if you want to sqash it yourself, please use our commit format "issue #1071 [message]")

**Comment by rishabhdeepsingh** [comment]
Let me do it for you. :D

**Comment by rishabhdeepsingh** [comment]
@aykborstelmann please have a look now :D

**Comment by rbudde** [comment]
@rishabhdeepsingh ayk is out of office this week. Pls wait until next week.

**Comment by aykborstelmann** [comment]
@rishabhdeepsingh  thank you for your contribution, it's merged now 👍🏻

**Pull request merged**
