### PR TITLE
issue #969 : named configuration loaded correctly with a program, but the name is then forgotten

### PR DESCRIPTION
**Pull request by LilMonk**
```gui.configuration.conf``` in guiState.model.js always remains an empty string.
So, whenever ```function configurationToBricklyWorkspace(xml)``` is called this line
```var name = xml == GUISTATE_C.getConfigurationConf() ? GUISTATE_C.getRobotGroup().toUpperCase() + "basis" : '';``` makes the ```name = ''``` and sets the configurationName as ' '.
I didn't get why ```gui.configuration.conf``` is needed. If mistaken please correct me.

### CODE REVIEW

**Comment by bjost2s** [comment]
Thank you very much for this pull request, in general your solution is correct, but we forgot to explain it a bit more in detail, there is a third option needed

- [x] the name, if it is a named configuration
- [x] [robot]basic, if it is a standard configuration
- [ ] empty or "", if it is a custom (modified standard) configuration

Please look in the issue again, we will write a comment there

**Comment by EthicalCoder99** [comment]
OK I will look into it. Can you assign me this issue.

**Comment by EthicalCoder99** [comment]
I have made some changes to the server-side. Please check if it's correct or not.

**Comment by bjost2s** [comment]
Thank you very much! Well done, this pull request is accepted here 27b84dc5f1460c68874625f7e6cbda91ea5a7ed8 and here 0fb503910c9fd0545ad931f3e9f4f5599984359b. We will have another internal review soon and then the bug fix will be released. One small issue, please try to install and use our formatters (see wiki) for further commits.

**Pull request closed without merging**
